#ifndef PAGINATIONPLUGIN_GLOBAL_H
#define PAGINATIONPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PAGINATIONPLUGIN_LIBRARY)
#  define PAGINATIONPLUGIN_EXPORT Q_DECL_EXPORT
#else
#  define PAGINATIONPLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // PAGINATIONPLUGIN_GLOBAL_H
